# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69e32bc5a20c3f1869e6f9354fdd08ce62bbb112bab8719db443e6347f0e8a9966e5404b6adc34f07f52ad4178ea961ec0ee298b4b2dedf857b0c4b0dd662099

test:
  secret_key_base: f5719c1347a13025d500cb4d9b7137e65ac6e82ab0178df7b0b7ccf1622b01f38e98eda4d075aabb3c2e1b0d93aeb6ea6b5d3aa142001607b725d2e6daebe2f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
